export const randomSuggestion = [
    "Did you actually just text me, or was that a pocket accident? 😏",
    "So, are we pretending this isn't awkward, or should we address it?",
    "On a scale of 1 to 'I overthink everything,' how's your day?",
    "Do you actually laugh at your own jokes, or is that just me?",
    "If I had a dollar for every bad decision I've made, I'd still be broke—because student loans.",
    "Why do you look like you text in all lowercase and mean it?",
    "Are you the person who replies instantly or disappears for 3-5 business days?",
    "What's your most ridiculous flex? Be honest.",
    "Did you eat today, or are you running on iced coffee and vibes? ☕",
    "I bet your Spotify Wrapped is just embarrassing noises and white noise playlists.",
    "Is this a normal conversation, or are you setting me up for a weird favor?",
    "Do you argue with Siri too, or am I just toxic?",
    "Your vibe says 'main character,' but your texts scream 'background extra.'",
    "Why do I feel like you're typing, deleting, and overthinking right now?",
    "What's your Hogwarts house, or are you one of those 'I didn't read Harry Potter' people?",
    "Do you have a favorite meme, or are you too cool for that?",
    "Tell me your favorite conspiracy theory, but make it spicy. 🌶️",
    "Do you ever cringe at things you did 5 years ago, or do you have inner peace?",
    "What's one thing you said you'd do in January and absolutely didn't? 🎯",
    "If awkward silences were Olympic sports, we'd get gold right now. 🥇",
    "Are you the 'just woke up' person or the 'up at 5 a.m. for no reason' person?",
    "Do you sleep with one pillow or an unnecessary mountain of them? 🛏️",
    "What's your most random midnight thought?",
    "If sarcasm were a love language, would you be fluent?",
    "How much of your life is just winging it and hoping for the best?",
    "If you could ghost one responsibility forever, which would it be?",
    "What's the most useless skill you've mastered?",
    "Have you ever texted someone first and regretted it immediately?",
    "If chaos were a brand, you'd be their ambassador. 🌀",
    "What's something that's 'none of my business,' but I need to know anyway?",
    "What's your worst 'I meant to send this to someone else' text story?",
    "What's the dumbest argument you've won and still feel proud of?",
    "Do you also procrastinate by cleaning, or are you mentally stable?",
    "What's the weirdest thing you've cried over? Be vulnerable. 🥲",
    "Are you the 'I have 100 alarms' type or 'I wake up naturally at 6 a.m.' type?",
    "If life were a reality show, what would your tagline be?",
    "What's your favorite way to waste time? Asking for science. 🧪",
    "What's one thing you'd ban if you were president? 🌎",
    "Would you survive in a horror movie, or would you trip immediately?",
    "What's something you've done that instantly made you think, 'I am so dumb'?",
    "What's your toxic trait, and can I top it?",
    "Why does texting you feel like waiting for a pigeon to deliver a letter?",
    "Do you think your pet judges you, or is that just mine? 🐾",
    "What's one trend you absolutely regret participating in?",
    "Do you also have random 3 a.m. existential crises, or am I just fun like that?",
    "Are you more 'listens to music while working' or 'vibes silently in chaos'?",
    "What's the pettiest reason you've unfriended someone?",
    "What's your worst 'this could've been an email' meeting story?",
    "Do you ever lie awake at night wondering why life is a group project?",
    "What's your worst attempt at 'trying to be cool'? Be honest.",
    "If overthinking was a sport, would you be an Olympian?",
    "What's your go-to move when you're bored? Asking for inspiration. 🎨",
    "Do you laugh at your own jokes, or do you just force others to?",
    "What's your most iconic 'no context needed' story?",
    "Have you ever started a fight you immediately regretted?",
    "Are you 'wakes up with perfect hair' or 'looks like a tornado' in the morning?",
    "What's your most irrational fear that even you can't explain?",
    "Do you think people actually read terms and conditions? 🤔",
    "What's the last thing you bought and immediately regretted?",
    "What's your guilty pleasure that you'd never admit IRL?",
    "If you could bring back one childhood snack, what would it be?",
    "Are you a 'responds with memes only' or 'novel-length texts' type?",
    "What's your funniest 'I can't believe I said that' moment?",
    "Do you think your phone judges you for how much you're on it? 📱",
    "What's your weirdest 'fun fact about me' flex?",
    "What's the last thing you ate that made you question your life choices?",
    "If you had a theme song for today, what would it be?",
    "Are you also bad at math, or is that just me manifesting chaos?",
    "What's the most random thing you've Googled today?",
    "Why does it feel like your autocorrect is out to sabotage you?",
    "If laziness was a sport, would you be an MVP?",
    "What's the weirdest compliment you've ever gotten?",
    "Do you think animals have opinions about us? 🐒",
    "If you could mute one person in real life, who would it be? 🎤",
    "What's the weirdest thing you've ever cried about?",
    "What's your survival strategy for awkward small talk?",
    "Why does every group chat eventually turn into chaos?",
    "What's the pettiest revenge you've ever taken?",
    "Are you 'morning coffee or nothing' or 'I survive on vibes alone'?",
    "If aliens landed, what's the one thing you'd show them to explain humanity?",
    "Do you think your dog would ghost you if they had social media? 🐕",
    "What's your go-to awkward situation escape line?",
    "If you could redo one cringe moment from your past, what would it be?",
    "Do you think online shopping counts as therapy?",
    "What's your 'I refuse to apologize for this' opinion?",
    "Do you ever just feel like your brain opened too many tabs?",
    "What's the most Gen Z thing you've ever said?",
    "If you had a dollar for every awkward moment, how rich would you be?",
    "Are you more 'Spotify playlist pro' or 'random shuffle chaos'?",
    "What's your go-to 'I'm bored but don't want to admit it' move?",
    "Why do I feel like you're reading this while avoiding something important? 😏"
  ];
  